base: &common
  google_plus: '<!-- Place this tag where you want the +1 button to render -->
<g:plusone></g:plusone><!-- Place this tag after the last plusone tag -->
<script type="text/javascript">(function(){var a=document.createElement("script");a.type="text/javascript";a.async=!0;a.src="https://apis.google.com/js/plusone.js";var b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)})();</script>'

  twitter_count: '<a href="http://twitter.com/share" class="twitter-share-button" data-count="horizontal">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>'

  twitter_no_count: '<a href="http://twitter.com/share" class="twitter-share-button" data-count="none">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>'

  facebook_like: '<iframe src="http://www.facebook.com/plugins/like.php?app_id=198442190209087&amp;href&amp;send=false&amp;layout=button_count&amp;width=450&amp;show_faces=true&amp;action=like&amp;colorscheme=light&amp;font=arial&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:450px; height:21px;" allowTransparency="true"></iframe>'

  facebook_like_send: '<div id="fb-root"></div><script src="http://connect.facebook.net/en_US/all.js#appId=198442190209087&amp;xfbml=1"></script><fb:like href="" send="true" layout="button_count" width="450" show_faces="true" font="arial"></fb:like>'

  stumble_upon: '<script src="http://www.stumbleupon.com/hostedbadge.php?s=2"></script>'

  linked_in_count: '<script type="text/javascript" src="http://platform.linkedin.com/in.js"></script><script type="in/share" data-counter="right"></script>'

  linked_in_no_count: '<script type="text/javascript" src="http://platform.linkedin.com/in.js"></script><script type="in/share"></script>'

development:
  <<: *common

production:
  <<: *common

test:
  <<: *common
